namespace SistemasWeb01.Models
{
    public class DbInitializer
    {
        public static void Seed(IApplicationBuilder applicationBuilder)
        {
            BethesdaPieShopDbContext context = applicationBuilder.ApplicationServices.CreateScope().ServiceProvider.GetRequiredService<BethesdaPieShopDbContext>();

            if (!context.Categorias.Any())
            {
                context.Categorias.AddRange(Categorias.Select(c => c.Value));
            }


            if (!context.Categories.Any())
            {
                context.Categories.AddRange(Categories.Select(c => c.Value));
            }

            if (!context.Pies.Any())
            {
                context.AddRange
                (
                    new Pie { Name = "Caramel Popcorn Cheese Cake", Price = 22.95M, ShortDescription = "The ultimate cheese cake", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake pie chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon pie muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart pie cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Cheese cakes"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/cheesecakes/caramelpopcorncheesecake.jpg", InStock = true, IsPieOfTheWeek = true, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/cheesecakes/caramelpopcorncheesecakesmall.jpg", AllergyInformation = "" },
                    new Pie { Name = "Chocolate Cheese Cake", Price = 19.95M, ShortDescription = "The chocolate lover's dream", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake pie chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon pie muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart pie cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Cheese cakes"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/cheesecakes/chocolatecheesecake.jpg", InStock = true, IsPieOfTheWeek = true, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/cheesecakes/chocolatecheesecakesmall.jpg", AllergyInformation = "" },
                    new Pie { Name = "Pistache Cheese Cake", Price = 21.95M, ShortDescription = "We're going nuts over this one", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake pie chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon pie muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart pie cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Cheese cakes"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/cheesecakes/pistachecheesecake.jpg", InStock = true, IsPieOfTheWeek = true, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/cheesecakes/pistachecheesecakesmall.jpg", AllergyInformation = "" },
                    new Pie { Name = "Pecan Pie", Price = 21.95M, ShortDescription = "More pecan than you can handle!", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake pie chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon pie muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart pie cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Fruit pies"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/fruitpies/pecanpie.jpg", InStock = true, IsPieOfTheWeek = false, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/fruitpies/pecanpiesmall.jpg", AllergyInformation = "" },
                    new Pie { Name = "Birthday Pie", Price = 29.95M, ShortDescription = "A Happy Birthday with this pie!", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake pie chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon pie muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart pie cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Seasonal pies"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/seasonal/birthdaypie.jpg", InStock = true, IsPieOfTheWeek = false, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/seasonal/birthdaypiesmall.jpg", AllergyInformation = "" },
                    new Pie { Name = "Apple Pie", Price = 12.95M, ShortDescription = "Our famous apple pies!", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake pie chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon pie muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart pie cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Fruit pies"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepie.jpg", InStock = true, IsPieOfTheWeek = false, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepiesmall.jpg", AllergyInformation = "" },
                    new Pie { Name = "Blueberry Cheese Cake", Price = 18.95M, ShortDescription = "You'll love it!", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake pie chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon pie muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart pie cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Cheese cakes"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/cheesecakes/blueberrycheesecake.jpg", InStock = true, IsPieOfTheWeek = false, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/cheesecakes/blueberrycheesecakesmall.jpg", AllergyInformation = "" },
                    new Pie { Name = "Cheese Cake", Price = 18.95M, ShortDescription = "Plain cheese cake. Plain pleasure.", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake pie chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon pie muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart pie cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Cheese cakes"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/cheesecakes/cheesecake.jpg", InStock = true, IsPieOfTheWeek = false, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/cheesecakes/cheesecakesmall.jpg", AllergyInformation = "" },
                    new Pie { Name = "Cherry Pie", Price = 15.95M, ShortDescription = "A summer classic!", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake pie chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon pie muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart pie cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Fruit pies"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cherrypie.jpg", InStock = true, IsPieOfTheWeek = false, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cherrypiesmall.jpg", AllergyInformation = "" },
                    new Pie { Name = "Christmas Apple Pie", Price = 13.95M, ShortDescription = "Happy holidays with this pie!", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake pie chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon pie muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart pie cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Seasonal pies"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/christmasapplepie.jpg", InStock = true, IsPieOfTheWeek = false, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/christmasapplepiesmall.jpg", AllergyInformation = "" },
                    new Pie { Name = "Cranberry Pie", Price = 17.95M, ShortDescription = "A Christmas favorite", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake pie chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon pie muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart pie cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Seasonal pies"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cranberrypie.jpg", InStock = true, IsPieOfTheWeek = false, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cranberrypiesmall.jpg", AllergyInformation = "" },
                    new Pie { Name = "Peach Pie", Price = 15.95M, ShortDescription = "Sweet as peach", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake pie chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon pie muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart pie cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Fruit pies"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/peachpie.jpg", InStock = false, IsPieOfTheWeek = false, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/peachpiesmall.jpg", AllergyInformation = "" },
                    new Pie { Name = "Pumpkin Pie", Price = 12.95M, ShortDescription = "Our Halloween favorite", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake pie chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon pie muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart pie cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Seasonal pies"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/pumpkinpie.jpg", InStock = true, IsPieOfTheWeek = false, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/pumpkinpiesmall.jpg", AllergyInformation = "" },
                    new Pie { Name = "Rhubarb Pie", Price = 15.95M, ShortDescription = "My God, so sweet!", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake pie chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon pie muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart pie cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Fruit pies"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/rhubarbpie.jpg", InStock = true, IsPieOfTheWeek = false, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/rhubarbpiesmall.jpg", AllergyInformation = "" },
                    new Pie { Name = "Strawberry Pie", Price = 15.95M, ShortDescription = "Our delicious strawberry pie!", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake pie chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon pie muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart pie cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Fruit pies"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberrypie.jpg", InStock = true, IsPieOfTheWeek = false, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberrypiesmall.jpg", AllergyInformation = "" },
                    new Pie { Name = "Strawberry Cheese Cake", Price = 18.95M, ShortDescription = "You'll love it!", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake pie chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon pie muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart pie cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Cheese cakes"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberrycheesecake.jpg", InStock = false, IsPieOfTheWeek = false, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberrycheesecakesmall.jpg", AllergyInformation = "" }
                );
            }
            if(!context.Products.Any())
            {
                context.AddRange
                    (
                    new Product { Name = "Vestido Ariel - Marino", Description = "Cuando el sol sale nos apetecen los estampados alegres y a todo color. Por eso hemos diseñado esta versión del vestido Ariel que es puro verano. Su patrón ya lo conoces, es nuestro top ventas máximo porque es perfecto para todas. Cruzado, con escote de pico y manguita corta. Ideal. Ya sabes, llévalo a la oficina, de compras o una cena de verano. La modelo mide 1,62m y lleva la talla 34.", Price = 36, Stock = 15, IsDeleted = false, IsNew = true, Categoria = Categorias["Vestidos"], ImageUrl = "/images/v1.webp" },
                    new Product { Name = "Vestido Bea - Crudo", Description = "El vestido más buscado de la temporada. Largo y de punto calado con apariencia croché. Perfectísimo para pasear junto al mar después de una jornada de playa, o para sentarte en una terraza con tus mejillas sonrosadas mientras brindas por la vida. Un vestido cómodo y con rollazo de edición limitada. Lleva vestidito de forro interior. La modelo de la talla 36/38 mide 1,62 m y la modelo de la talla 44/46 mide 1,58 m. 49%Algodón 49%Poliéster 2%Elastán", Price = 45, Stock = 10, IsDeleted = false, IsNew = true, Categoria = Categorias["Vestidos"], ImageUrl = "/images/v2.webp" },
                    new Product { Name = "Vestido Ariel - Fucsia", Description = "Cuando el sol sale nos apetecen los estampados alegres y a todo color. Por eso hemos diseñado esta versión del vestido Ariel que es puro verano. Su patrón ya lo conoces, es nuestro top ventas máximo porque es perfecto para todas. Cruzado, con escote de pico y manguita corta. Ideal. Ya sabes, llévalo a la oficina, de compras o una cena de verano.", Price = 37, Stock = 12, IsDeleted = false, IsNew = true, Categoria = Categorias["Vestidos"], ImageUrl = "/images/v3.webp" },
                    new Product { Name = "Vestido Pretty Lunares - Marrón", Description = "El vestido de la temporada, no tenemos pruebas pero tampoco dudas. De un patrón top y un estampado icónico, solo estamos pensando en estrenarlo. Su tejido es de crepe del que no se arruga, lleva bolsillos y puedes elegir si llevar los botones delante o en la espalda. Amamos. La modelo de la talla 36 mide 1,57 m y la modelo de la talla 44 mide 1,58 m. 100%Poliéste", Price = 36, Stock = 9, IsDeleted = false, IsNew = true, Categoria = Categorias["Vestidos"], ImageUrl = "/images/v4.webp" },
                    new Product { Name = "Vestido Alka - Negro", Description = "Hay vestidos y VESTIDOS. Ideal para una vichy addict como nosotras, este vestido es el look de la primavera. Nos encanta con complementos rojos, verdes, fucsias o amarillos. De corte recto y manguita estilo volante, lleva un botón en la espalda. ¡Qué ganas de estrenarlo! La modelo de la talla 36 mide 1,7 m y la modelo de la talla 44 mide 1,58 m.100%Viscosa", Price = 55, Stock = 10, IsDeleted = false, IsNew = true, Categoria = Categorias["Vestidos"], ImageUrl = "~/images/v5.webp" },
                    new Product { Name = "Falda Pantalón Allace - Mostaza", Description = "Dale estilo y color a tus looks con esta falda pantalón. Su tejido es una sarguita fluida elástica, ideal. Lleva cremallera lateral. La modelo de la talla 36 mide 1,57 m. 95%Poliéster 5%Elastán", Price = 55, Stock = 10, IsDeleted = false, IsNew = true, Categoria = Categorias["Faldas"], ImageUrl = "/images/f1.webp" },
                    new Product { Name = "Falda Ovar Lunares - Marrón", Description = "Verano, verbenas y fiesta. Esta falda invita a pasarlo bien y a bailar. La prenda perfecta para cerrar un look perfecto. Es de crepe y está toda fruncida por lo que sienta de maravilla y queda pegadita sin marcar. Lleva cremallera invisible en un lateral. La modelo de la talla 36 mide 1,57 m y la modelo de la talla 48 mide 1,58 m.  100%Poliéster", Price = 55, Stock = 10, IsDeleted = false, IsNew = true, Categoria = Categorias["Faldas"], ImageUrl = "/images/f2.webp" },
                    new Product { Name = "Falda Atria - Kaki", Description = "Ya sabes que esta temporada es (casi) obligatorio tener una falda denim midi. Reinventa la tendencia y pásate al color kaki. Nos flipa. Combínala con mil colores, es un tono neutro que queda de maravilla. Es de corte recto, con abertura en la parte de delante y bolsillos. Lista para dar rienda suelta a tus looks. La modelo de la talla 36 mide 1,57 m y la modelo de la talla 44 mide 1,58 m. 95%Algodón 5%Elastán", Price = 55, Stock = 10, IsDeleted = false, IsNew = true, Categoria = Categorias["Faldas"], ImageUrl = "/images/f3.webp" },
                    new Product { Name = "Falda Pantalón Lino Galis - Marrón", Description = "No nos gusta, ¡nos flipa! Hemos logrado la falda pantalón perfecta. Su color lima nos ha calado hondo y se ha convertido en nuestra prenda favorita. Estilo, fresca y cómoda. Lleva los botones decorativos al tono y cremallera invisible. La modelo de la talla 36 mide 1,57 m y la modelo de la talla 48 mide 1,58 m. 97%Algodón 3%Elastán", Price = 55, Stock = 10, IsDeleted = false, IsNew = true, Categoria = Categorias["Faldas"], ImageUrl = "/images/f4.webp" },
                    new Product { Name = "Falda Leresa Print - Multicolor", Description = "Sí rotundo a las faldas pareo. Nos apetece estrenar ya esta falda de crepe de un estampado que nos ha robado el corazón. Con lazada lateral, está lista para ser la prenda clave en tus looks tops de la temporada. La modelo de la talla 34 mide 1,54 m y la modelo de la talla 44 mide 1,58 m. 100%Poliéster", Price = 55, Stock = 10, IsDeleted = false, IsNew = true, Categoria = Categorias["Faldas"], ImageUrl = "/images/f5.webp" },
                    new Product { Name = "Camisa Idare - Blanco", Description = "Camisa blanca puño rizadito perfecta para llevarla suelta o para acompañar a tus jerséis favoritos. Gustosa y suave, a demás es apta para lactancia por sus botones reales. La modelo de la talla 34 mide 1,62 m y la modelo de la talla 44 mide 1,58 m. 97%Algodón 3%Elastán", Price = 55, Stock = 10, IsDeleted = false, IsNew = true, Categoria = Categorias["Camisetas y camisas"], ImageUrl = "/images/c1.webp" },
                    new Product { Name = "Top Lencero Nosdi - Negro", Description = "El top lencero es fondo de armario obligatorio. Y con esta preciosidad de top ni nos lo pensamos. Su tejido en crepe tiene mucha caída y movimiento, es de tirantitos y con una blonda en el escote como detalle al tono del top. Lo puedes combinar con pantalón o falda, tacón o zapatillas que irás espectacular. La modelo mide 1,57 m y lleva la talla 36. 100%Poliéster", Price = 55, Stock = 10, IsDeleted = false, IsNew = true, Categoria = Categorias["Camisetas y camisas"], ImageUrl = "/images/c2.webp" },
                    new Product { Name = "Top Lefilo - Marino", Description = "Para las amantes de los escotes halter y las prendas de punto este top es lo más. Muy versátil por su color y patrón, llévalo en todo tipo de ocasiones. La modelo de la talla 36 mide 1,57 m y la modelo de la talla 44 mide 1,58 m. 50% Acrilico 50% Algodón", Price = 55, Stock = 10, IsDeleted = false, IsNew = true, Categoria = Categorias["Camisetas y camisas"], ImageUrl = "/images/c3.webp" },
                    new Product { Name = "Top Lencero Nosdi - Bugambilia", Description = "El top lencero es fondo de armario obligatorio. Y con esta preciosidad de top ni nos lo pensamos. Su tejido en crepe tiene mucha caída y movimiento, es de tirantitos y con una blonda en el escote como detalle al tono del top. Lo puedes combinar con pantalón o falda, tacón o zapatillas que irás espectacular. La modelo mide 1,57 m y lleva la talla 36. 100%Poliéster", Price = 55, Stock = 10, IsDeleted = false, IsNew = true, Categoria = Categorias["Camisetas y camisas"], ImageUrl = "/images/c4.webp" },
                    
                    new Product { Name = "Mono Aliseda - Negro", Description = "El mono perfecto. Lo decimos sin lugar a dudas. Con el escote cruzado del que somos absolutas fans, manguita caída y tejido súper fluido que no necesita plancha. Una prenda que no puede faltar en tu armario y que utilizarás para lookazos de evento y para tu día a día. La modelo de la talla 36 mide 1,57 m y la modelo de la talla 34 mide 1,61 m. 100%Poliéster", Price = 55, Stock = 10, IsDeleted = false, IsNew = true, Categoria = Categorias["Pantalones y monos"], ImageUrl = "/images/m1.webp" },
                    new Product { Name = "Pantalón Gois - Marino", Description = "Sabemos que un pantalón marino es un imprescindible, y si este pantalón tiene ese toque especial, mejor que mejor. Fluído, con un tejido abambulado que es una pasada y con goma en la cintura. Una pasada de pantalón perfecto para tus días de oficina y tus vacaciones. La modelo de la talla 36 mide 1,58 m y la modelo de la talla 48 mide 1,58 m. 86%Rayon 14%Nylon", Price = 55, Stock = 10, IsDeleted = false, IsNew = true, Categoria = Categorias["Pantalones y monos"], ImageUrl = "/images/m2.webp" },
                    new Product { Name = "Pantalón Gois - Beige", Description = "Sabemos que un pantalón marino es un imprescindible, y si este pantalón tiene ese toque especial, mejor que mejor. Fluído, con un tejido abambulado que es una pasada y con goma en la cintura. Una pasada de pantalón perfecto para tus días de oficina y tus vacaciones. La modelo de la talla 36 mide 1,58 m y la modelo de la talla 48 mide 1,58 m.  84%Viscosa 14%Nylon", Price = 55, Stock = 10, IsDeleted = false, IsNew = true, Categoria = Categorias["Pantalones y monos"], ImageUrl = "/images/m3.webp" },
                    new Product { Name = "Short Ertin - Jeans", Description = "Ya están aquí las bermudas de la temporada. De un tejido súper elástico y cómodo, goma en la cintura y bolsillos. Nosotras ya nos hemos enamorado. El pantalón más versátil del momento tiene que ser tuyo. La modelo de la talla 36 mide 1,57 m y la modelo de la talla 48 mide 1,58 m. 76%Viscosa 21%Nylon 3%Elastán", Price = 55, Stock = 10, IsDeleted = false, IsNew = true, Categoria = Categorias["Pantalones y monos"], ImageUrl = "/images/m4.webp" },
                    new Product { Name = "Falda Pantalón Romal Vichy - Verde", Description = "Un toque fresco y chic para tus looks de temporada. Esta falda pantalón de cuadro vichy es lap renda que buscabas. Tiene la parte delantera de corte pareo con botoncitos nacarados. Lleva cremallera invisible en un lateral. La modelo mide 1,62 m y lleva la talla 34. 100%Algodón", Price = 55, Stock = 10, IsDeleted = false, IsNew = true, Categoria = Categorias["Pantalones y monos"], ImageUrl = "/images/m5.webp" },
                    new Product { Name = "Pantalón Gabriel - Kaki", Description = "La opción de colores tierra y naturales nos parece ideal también para primavera. Crea tus looks en estos tonos con este pantalón que es una pasada. Favorece 100%, su tiro es alto, lleva bolsillos y es de corte flare. Una auténtica pasada. La modelo de la talla 36 mide 1,57 m y la modelo de la talla 48 mide 1,58 m. 95%Algodón 5%Elastán", Price = 55, Stock = 10, IsDeleted = false, IsNew = true, Categoria = Categorias["Pantalones y monos"], ImageUrl = "/images/m6.webp" },
                    new Product { Name = "Biker Taran - Verde", Description = "Inauguramos por todo lo alto la temporada de bikers. En un tono verde ideal y de suave antelina elástica, esta es la biker que más vas a amar. Combínala con vestido, con vaqueros o con faldas, tienes el rollazo asegurado. Lleva bolsillos. La modelo de la talla 34 mide 1,62 m y la modelo de la talla 44 mide 1,58 m.", Price = 55, Stock = 10, IsDeleted = false, IsNew = true, Categoria = Categorias["Blazers y chaquetas"], ImageUrl = "/images/ch1.webp" },
                    new Product { Name = "Biker Taran - Negro", Description = "Inauguramos por todo lo alto la temporada de bikers. Imprescindible en negro y de suave antelina elastica, esta es la biker que más vas a amar. Combínala con vestido, con vaqueros o con faldas, tienes el rollazo asegurado. Lleva bolsillos. La modelo de la talla 34 mide 1,62 m y la modelo de la talla 44 mide 1,58 m. 95%Poliéster 5%Elastán", Price = 55, Stock = 10, IsDeleted = false, IsNew = true, Categoria = Categorias["Blazers y chaquetas"], ImageUrl = "/images/ch2.webp" },
                    new Product { Name = "Cárdigan Bego - Beige", Description = "Con la forma de un trench y la fluidez de un cárdigan, hemos creado el mix perfecto. Finito, no pesa y no se arruga, tu compañero perfecto para cuando se esconde el sol. Lleva cinturón del mismo tejido y manga sardineta, juega con su largo. La modelo de la talla 36 mide 1,57 m y la modelo de la talla 44 mide 1,58 m. 100%Poliéster", Price = 55, Stock = 10, IsDeleted = false, IsNew = true, Categoria = Categorias["Blazers y chaquetas"], ImageUrl = "/images/ch3.webp" }

                    );
            }

            context.SaveChanges();
        }

        private static Dictionary<string, Category>? categories;

        public static Dictionary<string, Category> Categories
        {
            get
            {
                if (categories == null)
                {
                    var genresList = new Category[]
                    {
                        new Category { CategoryName = "Fruit pies" },
                        new Category { CategoryName = "Cheese cakes" },
                        new Category { CategoryName = "Seasonal pies" }
                    };

                    categories = new Dictionary<string, Category>();

                    foreach (Category genre in genresList)
                    {
                        categories.Add(genre.CategoryName, genre);
                    }
                }

                return categories;
            }
        }

        private static Dictionary<string, Categoria>? categorias;

        public static Dictionary<string, Categoria> Categorias
        {
            get
            {
                if (categories == null)
                {
                    var genresList = new Categoria[]
                    {
                        new Categoria { Name = "Vestidos" },
                        new Categoria { Name = "Camisetas y camisas" },
                        new Categoria { Name = "Pantalones y monos" },
                        new Categoria { Name = "Faldas" },
                        new Categoria { Name = "Blazers y chaquetas" },
                        new Categoria { Name = "Ropa Deportiva" },
                        new Categoria { Name = "Premamá" },
                    };

                    categorias = new Dictionary<string, Categoria>();

                    foreach (Categoria genre in genresList)
                    {
                        categorias.Add(genre.Name, genre);
                    }
                }

                return categorias;
            }
        }
    }
}
